[source.crates-io]
registry = "https://github.com/rust-lang/crates.io-index"

# 指定镜像
replace-with = 'mirror'

# 本地vendor
[source.local]
directory = "vendor"

[source.mirror]
registry = "http://mirrors.tools.huawei.com/rust/crates.io-index/"

# 中国科学技术大学
[source.ustc]
registry = "https://mirrors.ustc.edu.cn/crates.io-index"

# 字节跳动
[source.rsproxy]
registry = "https://rsproxy.cn/crates.io-index"
